#! /bin/bash

t=`mktemp -t iomux-macrofy.XXXXXX`
trap "rm -f $t" EXIT

DEFS=$1

while read op fn mux_reg conf_reg inp_reg mux_mode inp_val; do
    test x"$op" = x'#define' || continue
    fn=`printf "%-40s\t" "$fn"`
    echo "s!\\b${mux_reg}[[:space:]]\\+${conf_reg}[[:space:]]\\+${inp_reg}[[:space:]]\\+${mux_mode}[[:space:]]\\+${inp_val}[[:space:]]\\+!$fn!gi"
done < $DEFS > $t

sed -f "$t"
