#! /bin/bash

BASE_NAME=elito_base
FINAL_NAME=elito-${RELEASE}
CONTAINER_HOSTNAME_devel=${FINAL_NAME}-${DISTRIBUTION}.`hostname -d`
CONTAINER_HOSTNAME_default=${FINAL_NAME}-${DISTRIBUTION}.`hostname -d`

: ${MODE:=default}

USER=ensc
EMAIL=enrico.scholz@sigma-chemnitz.de

NFSROOT_devel=/srv/sysroots/my-project/${FINAL_NAME}

# scripts assume that first location is the shared cache and the
# second the local build directory
VOLUMES_devel=(
  # a directory shared between multiple instances; does not need backup
  "/srv/.oe/docker/elito"

  # the build directory; it should be on a fast disk and does not need backup
  "/srv/.oe/docker/my-project"

  # the workspace with valuable files; it can be on a slow disk
  "/srv/projects/my-project"

  # read-only mirror
  "/srv/.oe/docker/mirror	''	:ro"

  # the NFS exported sysroot
  "${NFSROOT_devel}"
)

SYMLINKS_devel=(
  "/srv/.oe/docker/mirror	/srv/mirror"
  "/srv/.oe/docker/elito	/srv/cache"
)

# scripts assume that first location is the shared cache and the
# second the local build directory
VOLUMES_default=(
  "/srv/cache		$PWD/../docker/cache"
  "/srv/bld		$PWD/../docker/bld_${RELEASE}.${DISTRIBUTION}"
  "/srv/elito		$PWD/../docker/elito_${RELEASE}.${DISTRIBUTION}"
)

PORTS=(
    "22		base"
    "2049	next	2"
    "1234	next"
)

eval VOLUMES='( "${'VOLUMES_$MODE'[@]}" )'
eval CONTAINER_HOSTNAME=\$CONTAINER_HOSTNAME_$MODE
eval SYMLINKS='( "${'SYMLINKS_$MODE'[@]}" )'
eval _NFSROOT='( "${'NFSROOT_$MODE'[@]}" )'
