IMAGE_STREAM_PRESCRIPT ?=	${PROJECT_TOPDIR}/files/rescue-prescript
IMAGE_STREAM_POSTSCRIPT ?=	${PROJECT_TOPDIR}/files/rescue-postscript
IMAGE_STREAM_BOOTSTREAM0 ?=	${IMAGEDIR}/u-boot-$(MACHINE).sb
IMAGE_STREAM_BOOTSTREAM1 ?=	${IMAGEDIR}/rescue-zImage-$(MACHINE).sb
IMAGE_STREAM_KERNEL ?=		${IMAGEDIR}/zImage-$(MACHINE).bin
IMAGE_STREAM_ROOTIMG ?=		${IMAGEDIR}/elito-image-$(MACHINE).ext4

SKIP_PRESCRIPT =
SKIP_POSTSCRIPT =

SKIP_BOOTSTREAM0 =
SKIP_BOOTSTREAM1 =
SKIP_KERNEL =
SKIP_ROOTIMG =

SKIP_ANDROID_SYSTEM = t
SKIP_ANDROID_DATA = t
SKIP_ANDROID_CACHE = t

IMAGE_STREAM_deps = \
	${IMAGE_STREAM_BOOTSTREAM0} \
	${IMAGE_STREAM_BOOTSTREAM1} \
	${IMAGE_STREAM_KERNEL} \
	${IMAGE_STREAM_ROOTIMG}

ARGS = \
  $(call genopts,0x20000,PRESCRIPT,t) \
  $(call genopts,0x21000,BOOTSTREAM0) \
  $(call genopts,0x21001,BOOTSTREAM1) \
  $(call genopts,0x21002,KERNEL) \
  $(call genopts,0x22000,ROOTIMG) \
  $(call genopts,0x20001,POSTSCRIPT,t) \
