IMAGE_STREAM_PRESCRIPT ?=	${PROJECT_TOPDIR}/files/rescue-prescript
IMAGE_STREAM_POSTSCRIPT ?=	${PROJECT_TOPDIR}/files/rescue-postscript
IMAGE_STREAM_BOOTSTREAM ?=	${IMAGEDIR}/barebox-$(MACHINE).img
IMAGE_STREAM_DTREE ?=		${IMAGEDIR}/$(MACHINE).dtb
IMAGE_STREAM_KERNEL ?=		${IMAGEDIR}/zImage-$(MACHINE).bin
IMAGE_STREAM_ROOTIMG ?=		${IMAGEDIR}/elito-image-$(MACHINE).ext4
IMAGE_STREAM_RESCUE ?=		${IMAGEDIR}/rescue-$(MACHINE).imx

SKIP_STREAM_PRESCRIPT =
SKIP_STREAM_POSTSCRIPT =

SKIP_STREAM_BOOTSTREAM0 =
SKIP_STREAM_KERNEL =
SKIP_STREAM_ROOTIMG =

SKIP_STREAM_ANDROID_SYSTEM = t
SKIP_STREAM_ANDROID_DATA = t
SKIP_STREAM_ANDROID_CACHE = t

IMAGE_STREAM_deps = \
	${IMAGE_STREAM_BOOTSTREAM0} \
	${IMAGE_STREAM_KERNEL} \
	${IMAGE_STREAM_ROOTIMG}

ARG_PRESCRIPT  ?= $(call genopts,0x00001000,PRESCRIPT,t)
ARG_POSTSCRIPT ?= $(call genopts,0x000ff000,POSTSCRIPT,t)
ARG_BOOTSTREAM ?= $(call genopts,0x00002000,BOOTSTREAM)
ARG_KERNEL     ?= $(call genopts,0x00003000,KERNEL)
ARG_DTREE      ?= $(call genopts,0x00004000,DTREE)
ARG_FILESYSTEM ?= $(call genopts,0x00005000,ROOTIMG)
ARG_RESCUE     ?= $(call genopts,0x00009000,RESCUE)


ARGS ?= \
  ${ARG_PRESCRIPT} \
  ${ARG_BOOTSTREAM} \
  ${ARG_RESCUE} \
  ${ARG_KERNEL} \
  ${ARG_DTREE}\
  ${ARG_FILESYSTEM}\
  ${ARG_POSTSCRIPT}
