ifneq ($(wildcard /etc/docker-setup.mk),)
include /etc/docker-setup.mk

UNFSD_NFS_PORT ?=	${DOCKER_PORT_INTERNAL_0}
UNFSD_MOUNT_PORT ?=	${DOCKER_PORT_INTERNAL_1}
UNFSD_RPCNFSD_PORT ?=	${DOCKER_PORT_INTERNAL_2}
UNFSD_RPCMOUNTD_PORT ?=	${DOCKER_PORT_INTERNAL_3}

CFG_NFSOPTS_EXTRA = ,port=${DOCKER_PORT_EXPOSED_0},mountport=${DOCKER_PORT_EXPOSED_1}

# ,nfsprog=${DOCKER_PORT_INTERNAL_2},mountprog=${DOCKER_PORT_INTERNAL_3}

else ifneq (${UNFSD_PORT_BASE},)
UNFSD_NFS_PORT ?=	$$[ UNFSD_PORT_BASE + 0 ]
UNFSD_MOUNT_PORT ?=	$$[ UNFSD_PORT_BASE + 1 ]
UNFSD_RPCNFSD_PORT ?=	$$[ UNFSD_PORT_BASE + 2 ]
UNFSD_RPCMOUNTD_PORT ?=	$$[ UNFSD_PORT_BASE + 3 ]
else
endif

