#! /bin/bash

U=git://git.openembedded.org/bitbake
B='master 1.8 1.10 1.12 1.18 1.20 1.22 1.24'

d=`mktemp -t -d bitbake.XXXXXX` || exit 1
trap "rm -rf $d" EXIT

: ${OLD_BUNDLE:=`pwd`/bitbake-git.bundle}

test -r "$OLD_BUNDLE" || OLD_BUNDLE=

{
  cd $d
  git init --bare

  if test -n "$OLD_BUNDLE"; then
      git remote add old "$OLD_BUNDLE"
      git remote update
  fi

  for b in $B; do
      git fetch --no-tags "$U" $b:$b
  done

  test -z "$OLD_BUNDLE" || git remote rm old

  git -c gc.aggressiveWindow=1000 gc --aggressive
  git repack -a -d

  git ls-remote .

  tar cf - objects/pack/* --owner root --group root --mode 0644 >&3
  git bundle create bundle $B

  cat bundle >&4
  cd -
} 3> bitbake-git.tar.tmp 4>bitbake-git.bundle.tmp

rm -f bitbake-git.bundle bitbake-git.tar

mv bitbake-git.bundle.tmp bitbake-git.bundle
mv bitbake-git.tar.tmp bitbake-git.tar
