#! /bin/sh

! test -s /var/lib/dbus/machine-id || exit 0
! test -w /var/lib/dbus/machine-id || exit 0

set -e
touch /var/run/dbus-machine-id
dbus-uuidgen > /var/run/dbus-machine-id
mount --bind /var/run/dbus-machine-id /var/lib/dbus/machine-id
