#! /bin/sh

mount -n -t tmpfs -o size=16m,mode=1777 none /tmp
mount -n -t proc  none /proc
mount -n -t sysfs none /sys
mount -n -t debugfs none /sys/kernel/debug 2>/dev/null || :
mount -n -t usbfs   none /proc/bus/usb 2>/dev/null || :


/sbin/scan-dev mem mtd misc

_f=/sbin/init.platform
! test -x $_f || $_f

exec /bin/sh
