# --*- python -*--
#######################################

ELITO_OLD_CRUFT = "\
atk_1.30.0 \
bash_3.2.48 \
binutils_2.20.1 \
binutils_csl-arm-2008q1 \
binutils-cross_csl-arm-2008q1 \
binutils-cross_2.20.1 \
binutils-cross-canadian_2.20.1 \
binutils-crosssdk_2.20.1 \
bison_2.3 \
bluez4_4.82 \
cairo_1.10.0 \
connman_0.74 \
coreutils_6.9 \
cpio_2.8 \
diffutils_2.8.1 \
dosfstools_2.10 \
ed_0.5 \
findutils_4.2.31 \
gawk_3.1.5 \
gcc_csl-arm-2008q1 \
gcc-cross_csl-arm-2008q1 \
gcc-cross-initial_csl-arm-2008q1 \
gcc-cross-intermediate_csl-arm-2008q1 \
gettext_0.16.1 \
glib-2.0_2.27.5 \
gmp_4.2.1 \
gperf_3.0.3 \
grep_2.5.1a \
gtk+_2.12.7 \
gtk+_2.16.6 \
gzip_1.3.12 \
json-glib_0.10.4 \
libcanberra_0.26 \
libdrm_2.4.25 \
libgpg-error_1.8 \
libiconv_1.11.1 \
libidn_0.6.14 \
libx11_1.3.4 \
libxcb_1.1.91 \
m4_1.4.9 \
m4-native_1.4.9 \
matchbox-desktop_0.9.1 \
midori_0.2.9 \
mpfr_3.0.0 \
mtools_3.9.9 \
nfs-utils_1.1.2 \
openssl_0.9.8m \
openssl_0.9.8r \
pango_1.28.3 \
patch_2.5.9 \
pulseaudio_0.9.15 \
pulseaudio_0.9.22 \
readline_5.2 \
rsync_2.6.9 \
sed_4.1.2 \
tar_1.17 \
which_2.18 \
which_2.18 \
xserver-xorg_1.9.4 \
"

############################################

PKGDUP_IGNORES = " \
cross-localedef-native_2.12 \
eglibc_2.12 \
eglibc-initial_2.12 \
eglibc-locale_2.12 \
liberation-fonts_1.04 \
upstart-setup_devel \
"
