#! /bin/sh

function uuidgen() {
    ! test -s "$1" || return 0

    if test -w "$1"; then
	rm -f "$1"
    else
	/usr/bin/dbus-uuidgen --ensure="$2"
	/bin/mount --bind "$2" "$1"
    fi
}

! test -s /etc/machine-id || exit 0
! test -w /etc/machine-id || exit 0

! test -s /var/lib/dbus/machine-id || exit 0
! test -w /var/lib/dbus/machine-id || exit 0

set -e

uuidgen /var/lib/dbus/machine-id /var/run/dbus-machine-id
uuidgen /etc/machine-id /var/run/dbus-machine-id
