#! /bin/sh

case "$1" in
  start)

    echo -n "Scanning for cold-plugged devices..."

    for i in /sys/class/block/*/uevent; do
        test -e "$i" || continue
  	echo add > "$i"
    done

    echo " done"
    ;;
esac
