#! /bin/bash

CGDIR=/sys/fs/cgroup
CNAME=$1
shift

test -d "$CGDIR" || exit 0
test -r /proc/self/cgroup || exit 0

while read; do
    case $REPLY in
      (*:name=systemd:*)
      tmp=${REPLY##*:name=systemd:}

      case $tmp in
	# RH19 style
	*.session)
	      ldir=$CGDIR/systemd/$tmp/$CNAME
	      ;;

	# RH20+ style
	*/user.slice/user-$UID.slice/session-*.scope)
	      ldir=$CGDIR/systemd/$tmp/../user@$UID.service/$CNAME
	      ;;

	/system.slice/docker-*)
	      ldir=
	      ;;

	*)
	      echo "Unknown cgroup style '$tmp'" >&2
	      ldir=
	      ;;
      esac

      test -n "$ldir"  || exit 0
      mkdir -p "$ldir" || exit 1

      for i; do
	  echo $i > "$ldir"/tasks
      done
      ;;
    esac
done < /proc/self/cgroup
