#! /bin/bash

: ${BRANCHES:=heads/master}
D=$1				# destination
S=$2				# source
R=$3				# last tag/release
REL_D=$4

panic() {
    echo "$*" >&2
    exit 1
}

validate_rev() {
    test "$#" -eq 1 || panic "Bad revision $*"
}

shift 4 || panic "Missing arguments"

set -e
mkdir "$D"


if test -n "$R"; then
    _r=`$GIT ls-remote "$S" $R | cut -f 1`
    validate_rev $_r
    _r=^$_r
else
    _r=
fi

if test -d "$REL_D"; then
    cd "$REL_D"

    case x`$GIT config core.bare` in
      (xtrue)
	    touch $D/bare
	    ;;
    esac

    cd -
fi

cd "$S"

$GIT bundle create $D/bundle $BRANCHES $_r "$@" || :

test -z "$BRANCHES" || \
    $GIT ls-remote "$S" $BRANCHES > "$D/branches"

test -z "$TAGS" || \
    $GIT ls-remote --tags "$S" $TAGS > "$D/tags"

echo "$REL_D" > "$D/dir"

ls -l $D
