#! /bin/bash

test -r "$1" || {
  echo "**** Can not read '$1'. Try"
  echo "        make bitbake-clean && make init"
  echo "***** again."
  exit 1
} >&2

d=/work-shared/\${MACHINE}/elito-makefile/recipe-sysroot-native/usr/bin

cat <<EOF
__w=\${W_:-$2}
PSEUDO_BINDIR="\$__w$d"
PSEUDO_LIBDIR="\$__w$d/../lib/pseudo/lib"
PSEUDO_PREFIX="\$__w$d/../.."
PSEUDO_DISABLED=1
PSEUDO=\$PSEUDO_BINDIR/pseudo
export PSEUDO_BINDIR PSEUDO_LIBDIR PSEUDO_PREFIX PSEUDO_DISABLED
unset __w
EOF
