#! /bin/bash

## Usage: run-pseudo <abs_top_builddir> <prog> [<args>*]

_cmd=`type -P "$2"`
if ! test -x "$_cmd"; then
    echo "***** Could not find bitbake binary. Make sure that it was"
    echo "***** checked out by 'make init' in your project directory"
    exit 1
fi >&2
unset _cmd

BB_ENV_EXTRAWHITE='W CCACHE_DIR HOME GIT_SSL_CAINFO '\
'ftp_proxy http_proxy https_proxy no_proxy '\
'ELITO_CRT ELITO_KEY ELITO_PROG_SSL_CLIENT ELITO_USE_LIBPROXY ELITO_PROG_PROXY '\
'PSEUDO_BUILD PSEUDO_DISABLED '\
'ELITO_METRICS_ID BB_NUMBER_THREADS'

BBFETCH2=True
export BB_ENV_EXTRAWHITE PSEUDO_BUILD BBFETCH2

. "$1/set-env"

PSEUDO=
export -n PSEUDO

case x$PSEUDO_BUILD in
  (x0)
	unset PSEUDO_BUILD
	;;
  (x1)
	;;

  (x|x*)
	PSEUDO_BUILD=2
	test -e "$1/.tmp/pseudo.env" || {
	  echo "***** Could not find bitbake environment. Try"
	  echo "        make bitbake-clean && make init"
	  echo "***** again."
	  exit 1
	} >&2

	. "$1/.tmp/pseudo.env"
	;;
esac

_prog=$2
shift 2

test -z "$ELITO_CGROUP_NAME" || "$ELITO_SCRIPTS_DIR"/exec-cgroup "$ELITO_CGROUP_NAME" $$
exec_secure $PSEUDO "$_prog" "$@"
