#! /bin/bash

BASE_NAME=elito_base
FINAL_NAME=elito-${RELEASE}
CONTAINER_HOSTNAME_default=${FINAL_NAME}-${DISTRIBUTION}.`hostname -d`

: ${MODE:=default}

VOLUMES_default=(
  "/srv/cache		$PWD/../docker/cache"
  "/srv/bld		$PWD/../docker/bld_${RELEASE}.${DISTRIBUTION}"
  "/srv/elito		$PWD/../docker/elito_${RELEASE}.${DISTRIBUTION}"
)

eval VOLUMES='( "${'VOLUMES_$MODE'[@]}" )'
eval CONTAINER_HOSTNAME=\$CONTAINER_HOSTNAME_$MODE
eval SYMLINKS='( "${'SYMLINKS_$MODE'[@]}" )'
eval _NFSROOT='( "${'NFSROOT_$MODE'[@]}" )'
